# Generated by Django 4.1.3 on 2022-12-05 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='expereince_time',
            new_name='experience_time',
        ),
    ]
